### ISSUE TITLE
Can't resolve 'heatmap.js' in '......\node_modules\ngx-heatmap'

### ISSUE THREAD

**Issue by yogeshpaisode** [sanuradhag/ngx-heatmap#3]
Hello,

I am using angular 6 CLI, and getting following error.

ERROR in ./node_modules/ngx-heatmap/ngx-heatmap.umd.js
Module not found: Error: Can't resolve 'heatmap.js' in '......\node_modules\ngx-heatmap'

**Comment by sainik18** [comment]
I'm also facing same issue :(

**Comment by andreagosto** [comment]
The same for me..

**Comment by andreagosto** [comment]
in the package.json of this library, i saw that "heatmap.js": "^2.0.5", is a dependency: adding this dependency in my package.json,  the project now compiles
see
https://github.com/sanuradhag/ngx-heatmap/blob/master/package.json

**Comment by ashis1** [comment]
npm install heatmap.js
this common in your cmd or terminal will solve this issue

**Comment by sanuradhag** [comment]
updated the library to support angular 9. Now it should work. Read the read me of the NPM package before installing the package
