### ISSUE TITLE
Package "ngx-heatmap" has an incompatible peer dependency

### ISSUE THREAD

**Issue by LoganDupont** [sanuradhag/ngx-heatmap#4]
When I tried to update my angular to `7.2.15` with `ng update @angular/core` I received the following message 
`Package "ngx-heatmap" has an incompatible peer dependency to "@angular/core" (requires "^4.0.0" (extended), would install "7.2.15").`
`Package "ngx-heatmap" has an incompatible peer dependency to "rxjs" (requires "^5.1.0", would install "6.5.2").`

So it seems that we have still some old dependencies in this package.

**Comment by ashis1** [comment]
npm install heatmap.js will solve this issue

**Comment by BeMoreHuman** [comment]
Current version: `Angular: 6.0.3`
Tried to update: `ng update @angular/cli@7 @angular/core@7`
And received following message:
`Package "ngx-heatmap" has an incompatible peer dependency to "@angular/core" (requires ">=5.0.0-rc.0 <6.0.0||>=4.0.0 <5.0.0", would install "7.2.16").`
* `npm install heatmap.js` doesn't resolve the problem

**Comment by sanuradhag** [comment]
Updated the version, which supports angular 9. Closing this issue
